require('dotenv').config();
const { Client, GatewayIntentBits } = require('discord.js');
const fs = require('fs');
const path = require('path');

// One-time migration: re-upload the bot's hardcoded guild emojis as APPLICATION
// emojis (owned by the bot, usable in every server) and rewrite
// src/constants/appEmojis.js with the new ids.
//
// Run once:  node migrate-emojis.js
//
// Safe to re-run: emojis that already exist on the application are reused.

const APP_EMOJIS_FILE = path.join(__dirname, 'src', 'constants', 'appEmojis.js');
const { emojis: SOURCE } = require(APP_EMOJIS_FILE);

console.log('\n╔══════════════════════════════════════════════╗');
console.log('║      Mira Bot - Application Emoji Migrate     ║');
console.log('╚══════════════════════════════════════════════╝\n');

async function fetchBuffer(url) {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`download ${res.status} for ${url}`);
    return Buffer.from(await res.arrayBuffer());
}

function renderAppEmojisFile(result) {
    const lines = Object.entries(result).map(([key, e]) => {
        const namePad = `'${e.name}',`.padEnd(13);
        return `    ${(key + ':').padEnd(12)}{ name: ${namePad} id: '${e.id}', animated: ${e.animated} },`;
    });

    return `// Application (bot-owned) emojis.
//
// These render in ANY server the bot is in, so the bot no longer depends on the
// original home guild for its custom emojis. Generated by \`node migrate-emojis.js\`.

const emojis = {
${lines.join('\n')}
};

// Full markup string, e.g. "<a:loading:123>" — for use in message/embed text.
function markup(key) {
    const e = emojis[key];
    if (!e) return '';
    return \`<\${e.animated ? 'a' : ''}:\${e.name}:\${e.id}>\`;
}

// Raw id — for ButtonBuilder#setEmoji().
function id(key) {
    return emojis[key] ? emojis[key].id : null;
}

module.exports = { emojis, markup, id };
`;
}

const client = new Client({ intents: [GatewayIntentBits.Guilds] });

client.once('ready', async () => {
    try {
        await client.application.fetch();

        // Existing application emojis, keyed by name (so re-runs reuse them)
        const existing = await client.application.emojis.fetch();
        const byName = new Map();
        for (const e of existing.values()) byName.set(e.name, e);

        const result = {};

        for (const [key, src] of Object.entries(SOURCE)) {
            if (byName.has(src.name)) {
                const e = byName.get(src.name);
                result[key] = { name: e.name, id: e.id, animated: e.animated || false };
                console.log(`  ↩ reused existing :${e.name}: (${e.id})`);
                continue;
            }

            const url = `https://cdn.discordapp.com/emojis/${src.id}.${src.animated ? 'gif' : 'png'}?size=128&quality=lossless`;
            try {
                const attachment = await fetchBuffer(url);
                const created = await client.application.emojis.create({ attachment, name: src.name });
                result[key] = { name: created.name, id: created.id, animated: created.animated || false };
                console.log(`  ✓ uploaded :${created.name}: (${created.id})`);
            } catch (err) {
                console.error(`  ✗ failed :${src.name}: — ${err.message} (keeping old id ${src.id})`);
                result[key] = { ...src };
            }
        }

        fs.writeFileSync(APP_EMOJIS_FILE, renderAppEmojisFile(result));
        console.log(`\n📝 wrote ${APP_EMOJIS_FILE}`);
        console.log('\n╔══════════════════════════════════════════════╗');
        console.log('║            Emoji Migration Done! 🎉          ║');
        console.log('╚══════════════════════════════════════════════╝\n');
    } catch (err) {
        console.error('\n❌ migration failed:\n', err);
        process.exitCode = 1;
    } finally {
        client.destroy();
    }
});

client.login(process.env.DISCORD_TOKEN);
